// GitHub Pages -> local/tunneled backend during testing.
// Replace the URL below with the HTTPS URL generated by your tunnel.
// Example: https://bunbun-api.trycloudflare.com
window.BUNBUN_API_BASE = "https://YOUR-TUNNEL-URL";
